import PageHeader from "../components/PageHeader"

function Inversiones() {
    return (
        <>
            <PageHeader titulo="Inversiones" />
            <section id="inversiones" className='padded'>
                <div className="container">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa quia explicabo magnam voluptate facilis officia corrupti reiciendis dicta libero quos. Illum dolorum, alias maxime accusamus dolore illo impedit quae ipsam adipisci eum velit ea nihil quas eligendi explicabo error ex repudiandae amet labore. Quam, iure dolores beatae placeat aperiam harum a et dolor ullam possimus veritatis corporis, sit sapiente suscipit quos ipsam reiciendis vero, nulla est quibusdam voluptatibus! Consequatur, voluptas consectetur. Veritatis rerum assumenda tempore repellat maxime voluptate praesentium quae laborum? Sapiente vitae voluptates officia eveniet illo recusandae fugit, cupiditate atque animi praesentium reprehenderit optio eaque blanditiis incidunt ea facilis modi esse dignissimos similique repudiandae autem veniam sit aliquam. Earum et aut, obcaecati amet voluptatem quam placeat fugiat officia omnis!</p>
                    <p>Velit delectus atque praesentium unde dignissimos officiis non? Impedit quisquam voluptate ipsa hic fuga quae, velit, obcaecati molestiae provident eaque corrupti necessitatibus, nesciunt nobis maiores ipsum ratione at veniam error voluptatem explicabo fugiat ullam et! Tenetur aspernatur quod ea, quo maiores mollitia repellat ab non ullam odio architecto placeat cum ipsa, laudantium deleniti sapiente quaerat quibusdam. Sit, neque. Obcaecati itaque similique ipsum adipisci qui aliquid placeat, recusandae eaque earum inventore ea. Dolore repellendus a adipisci voluptatibus ducimus magnam, expedita soluta quae molestias ipsum, debitis deserunt repudiandae vitae nesciunt explicabo dolores sapiente suscipit cupiditate ipsam modi rerum! Aliquam, sapiente doloremque quibusdam earum quidem fuga, accusantium sit quae fugiat, labore sunt ab voluptatem similique laborum quisquam maxime architecto quaerat hic accusamus! Cupiditate.</p>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Officia accusamus mollitia rem quisquam reiciendis ab laborum, dignissimos, qui sint numquam reprehenderit voluptatibus? Quia consectetur enim repellat illum inventore eum unde laudantium nostrum ut et! Fuga odio itaque explicabo voluptatum expedita suscipit architecto recusandae autem. A alias ullam sint, perspiciatis dolores explicabo adipisci, unde eveniet soluta facilis non est obcaecati eos saepe officia corrupti earum assumenda reprehenderit ipsum nulla ut. Aut ad atque, aspernatur voluptatem veritatis deserunt maiores doloribus quam fuga aperiam. Sapiente ea minus nostrum excepturi voluptatibus iste eligendi qui, doloribus explicabo voluptatem, voluptates nam itaque unde. Ratione voluptas assumenda, amet saepe modi qui, pariatur earum ipsa numquam adipisci illo dolore. Doloribus culpa dignissimos eius, voluptatum ipsa veritatis totam quidem!</p>
                    <p>Dicta impedit ducimus molestias repellat atque cumque minima quod debitis voluptatibus vitae iste eligendi dignissimos dolores, a praesentium incidunt perferendis. Magni, necessitatibus ipsam accusantium quas labore expedita est quia vel magnam ratione assumenda at consequatur, facere obcaecati inventore quam! Excepturi dolor animi eveniet non expedita tempora error, totam officiis accusantium iusto suscipit reiciendis omnis et earum delectus deserunt quas fuga sapiente similique facere, sit nam commodi reprehenderit doloremque! Itaque esse dolorem odit nemo voluptatibus illum odio maiores, explicabo at aliquam perspiciatis eveniet iure officiis fugit hic cupiditate ipsa accusamus accusantium exercitationem harum quasi rerum nihil voluptate dicta! Ducimus corrupti culpa maxime distinctio. Sequi cum, mollitia, sed deleniti dolorum provident tempora qui porro in eveniet optio, sit delectus dolorem eius modi.</p>
                    <p>Fugit fuga ducimus fugiat eius optio odio libero neque quidem iure enim. Et voluptatibus eum consectetur quos itaque ex, laboriosam eveniet voluptate labore odit praesentium tempora. Praesentium similique labore tenetur ullam neque quasi, adipisci id nulla cumque! Deserunt voluptatibus ex amet eligendi quidem porro veritatis optio hic provident consequuntur, debitis corporis laudantium magnam minima repudiandae doloremque aspernatur possimus perferendis facilis deleniti. Ipsa eaque voluptas delectus atque minima alias voluptatum fugit quas magni iusto dolorem blanditiis voluptates eos minus quibusdam esse, nulla quidem in provident ratione impedit dolorum. Maxime, id minus numquam cum iure non beatae consequuntur, dicta corporis pariatur a recusandae tempora, eos aliquam! Molestiae eius atque expedita autem itaque at eligendi, iusto distinctio repellendus harum quam sapiente, consequatur exercitationem!</p>
                </div>
            </section>
        </>
    )
}

export default Inversiones